# Generated by Django 5.0.6 on 2024-06-07 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_geo_address_geo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='geo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.geo'),
        ),
    ]
